import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import TurnstileBox from '../components/TurnstileBox';
export default function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ email: 'admin@jakartamax.local', password: 'Admin#12345' }); const [captchaToken, setCaptchaToken] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setLoading(true); try { await login({ ...form, captchaToken }); navigate('/'); } catch (err) { setError(err.response?.data?.message || 'Login gagal'); } finally { setLoading(false); } }
  return <div className="min-h-screen grid lg:grid-cols-2"><div className="hidden lg:flex bg-slate-950 text-white p-12 flex-col justify-between"><div><div className="inline-flex items-center gap-3 rounded-full bg-white/10 px-4 py-2 text-sm"><ShieldCheck size={18} />Jakarta Max Owners</div><h1 className="mt-8 text-5xl font-bold leading-tight">Enterprise Kas Kecil & Kas Besar</h1><p className="mt-5 text-slate-300 max-w-lg">Dashboard modern untuk pemasukan, pengeluaran, approval 3 approver, audit log, dan laporan UAT.</p></div><div className="text-sm text-slate-400">Port default: 5700 • Node.js • PostgreSQL • React</div></div><div className="grid place-items-center bg-slate-100 p-6"><form onSubmit={submit} className="card w-full max-w-md p-8"><h2 className="text-2xl font-bold text-slate-900">Sign in</h2><p className="mt-2 text-sm text-slate-500">Masuk ke sistem keuangan Jakarta Max Owners</p><div className="mt-6"><label className="label">Email</label><input className="input" value={form.email} onChange={(e) => setForm((v) => ({ ...v, email: e.target.value }))} /></div><div className="mt-4"><label className="label">Password</label><input type="password" className="input" value={form.password} onChange={(e) => setForm((v) => ({ ...v, password: e.target.value }))} /></div><div className="mt-4"><TurnstileBox onToken={setCaptchaToken} /></div>{error && <div className="mt-4 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<button disabled={loading} className="btn-primary mt-6 w-full">{loading ? 'Signing in...' : 'Login'}</button><div className="mt-6 text-xs text-slate-500">UAT default: admin@jakartamax.local / Admin#12345</div></form></div></div>;
}
