import { useEffect, useMemo, useState } from 'react';
import http from '../api/http';
export default function ReportsPage() {
  const [filters, setFilters] = useState({ cashType: '', flow: '', status: '', fromDate: '', toDate: '' }); const [rows, setRows] = useState([]);
  const queryString = useMemo(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.append(key, value); }); return params.toString(); }, [filters]);
  async function load() { const { data } = await http.get(`/reports${queryString ? `?${queryString}` : ''}`); setRows(data); }
  useEffect(() => { load(); }, [queryString]);
  function download(type) { const base = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5700/api'; const token = localStorage.getItem('jmo_token'); const url = `${base}/reports/export/${type}${queryString ? `?${queryString}` : ''}`; fetch(url, { headers: { Authorization: `Bearer ${token}` } }).then(async (res) => { const blob = await res.blob(); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = type === 'xlsx' ? 'jmo-report.xlsx' : 'jmo-report.pdf'; a.click(); }); }
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">Laporan</h1><p className="mt-1 text-slate-500">Filter data dan export ke XLSX atau PDF.</p></div><div className="card p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><select className="input" value={filters.cashType} onChange={(e) => setFilters({ ...filters, cashType: e.target.value })}><option value="">Semua Kas</option><option value="kas_kecil">Kas Kecil</option><option value="kas_besar">Kas Besar</option></select><select className="input" value={filters.flow} onChange={(e) => setFilters({ ...filters, flow: e.target.value })}><option value="">Semua Arus</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select><select className="input" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Semua Status</option><option value="approved">Approved</option><option value="pending_approval">Pending Approval</option><option value="rejected">Rejected</option></select><input className="input" type="date" value={filters.fromDate} onChange={(e) => setFilters({ ...filters, fromDate: e.target.value })} /><input className="input" type="date" value={filters.toDate} onChange={(e) => setFilters({ ...filters, toDate: e.target.value })} /></div><div className="mt-4 flex flex-wrap gap-3"><button className="btn-primary" onClick={() => download('xlsx')}>Export XLSX</button><button className="btn-secondary" onClick={() => download('pdf')}>Export PDF</button></div></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-4 py-3">Tanggal</th><th className="px-4 py-3">Kas</th><th className="px-4 py-3">Arus</th><th className="px-4 py-3">Kategori</th><th className="px-4 py-3">Deskripsi</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{rows.map((row, idx) => <tr key={idx} className="border-t border-slate-100"><td className="px-4 py-3">{row.transaction_date.slice(0,10)}</td><td className="px-4 py-3">{row.cash_type}</td><td className="px-4 py-3">{row.flow}</td><td className="px-4 py-3">{row.category}</td><td className="px-4 py-3">{row.description}</td><td className="px-4 py-3">Rp {Number(row.amount).toLocaleString('id-ID')}</td><td className="px-4 py-3">{row.status}</td></tr>)}</tbody></table></div></div></div>;
}
